[aws]
symbol = "  "

[buf]
symbol = " "

[directory]
read_only = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
#format = '\[[$time]($style)\]'

#[username]
#style_user = "white bold"
#style_root = "black bold"
#format = '\[[$user]($style)\]'
#show_always = true

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[battery]
full_symbol = ""
charging_symbol = "⚡️"
discharging_symbol = ""

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = ""

# [localip]
# ssh_only = false
# format = "@[$localipv4](bold red) "
# disabled = false
